"""users table

Revision ID: 25b15ff37c04
Revises: f3d19d240e09
Create Date: 2019-09-10 23:36:37.936420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b15ff37c04'
down_revision = 'f3d19d240e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usertype', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'usertype')
    # ### end Alembic commands ###
