"""empty message

Revision ID: 2fdff62e99a5
Revises: 3c29086c2458
Create Date: 2019-10-12 19:21:17.088726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fdff62e99a5'
down_revision = '3c29086c2458'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaching_class', sa.Column('coachingimage_filename', sa.String(), nullable=True))
    op.add_column('coaching_class', sa.Column('coachingimage_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaching_class', 'coachingimage_url')
    op.drop_column('coaching_class', 'coachingimage_filename')
    # ### end Alembic commands ###
