"""empty message

Revision ID: 3a26fa75c3af
Revises: a984b151d9cd
Create Date: 2019-10-29 12:55:36.621825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a26fa75c3af'
down_revision = 'a984b151d9cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaching_teachers', sa.Column('image_filename', sa.String(), nullable=True))
    op.add_column('coaching_teachers', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coaching_teachers', 'image_url')
    op.drop_column('coaching_teachers', 'image_filename')
    # ### end Alembic commands ###
