"""empty message

Revision ID: 4bc6d443664e
Revises: e35cf64c9431
Create Date: 2019-12-13 23:12:52.789371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bc6d443664e'
down_revision = 'e35cf64c9431'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_coaching_relation', 'CoachingStubject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_coaching_relation', sa.Column('CoachingStubject', sa.VARCHAR(length=140), nullable=True))
    # ### end Alembic commands ###
