"""empty message

Revision ID: 53026f391703
Revises: 1a1353857126
Create Date: 2020-01-31 23:15:55.556997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53026f391703'
down_revision = '1a1353857126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('studentfathersname', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('studentqualification', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_details', schema=None) as batch_op:
        batch_op.drop_column('studentqualification')
        batch_op.drop_column('studentfathersname')

    # ### end Alembic commands ###
