"""empty message

Revision ID: 657bc2cf8180
Revises: d1fedd0857af
Create Date: 2019-10-31 15:01:13.157000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657bc2cf8180'
down_revision = 'd1fedd0857af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coaching_teachers', 'coaching_class', ['coaching_id1'], ['coachingid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coaching_teachers', type_='foreignkey')
    # ### end Alembic commands ###
