"""empty message

Revision ID: a55c5d1f0852
Revises: 6603b2ca78ea
Create Date: 2020-01-24 22:40:04.546745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a55c5d1f0852'
down_revision = '6603b2ca78ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batchIsActive', sa.String(length=140), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaching_batches', schema=None) as batch_op:
        batch_op.drop_column('batchIsActive')

    # ### end Alembic commands ###
