"""empty message

Revision ID: a984b151d9cd
Revises: 2fdff62e99a5
Create Date: 2019-10-28 20:21:05.076352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a984b151d9cd'
down_revision = '2fdff62e99a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teachersname', sa.String(length=140), nullable=True),
    sa.Column('teachersqualification', sa.String(length=140), nullable=True),
    sa.Column('teacherssubject', sa.String(length=140), nullable=True),
    sa.Column('teachersexperience', sa.String(length=140), nullable=True),
    sa.Column('user_id2', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id2'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaching_teachers')
    # ### end Alembic commands ###
