"""empty message

Revision ID: c404cb51ccb8
Revises: cfe6bf53fb21
Create Date: 2019-09-16 18:46:17.282447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c404cb51ccb8'
down_revision = 'cfe6bf53fb21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'coaching_class', 'user', ['user_id'], ['id'])
    op.add_column('post', sa.Column('user_id1', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id1'], ['id'])
    op.drop_column('post', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    op.drop_column('post', 'user_id1')
    op.drop_constraint(None, 'coaching_class', type_='foreignkey')
    # ### end Alembic commands ###
