"""empty message

Revision ID: d1fedd0857af
Revises: 3a26fa75c3af
Create Date: 2019-10-31 15:00:55.699156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1fedd0857af'
down_revision = '3a26fa75c3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coaching_teachers', sa.Column('coaching_id1', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'coaching_teachers', 'coaching_class', ['coaching_id1'], ['coachingid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coaching_teachers', type_='foreignkey')
    op.drop_column('coaching_teachers', 'coaching_id1')
    # ### end Alembic commands ###
