"""empty message

Revision ID: d675de0baef2
Revises: fdea45df250d
Create Date: 2019-12-20 21:44:50.906827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd675de0baef2'
down_revision = 'fdea45df250d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batchname', sa.String(length=140), nullable=True),
    sa.Column('batchdescription', sa.String(length=140), nullable=True),
    sa.Column('batchstartdate', sa.String(length=140), nullable=True),
    sa.Column('batchenddate', sa.String(length=140), nullable=True),
    sa.Column('batchfees', sa.Integer(), nullable=True),
    sa.Column('user_idB', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_idB'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaching_batches')
    # ### end Alembic commands ###
