"""empty message

Revision ID: dabc35687bdd
Revises: 657bc2cf8180
Create Date: 2019-12-12 00:00:26.665200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabc35687bdd'
down_revision = '657bc2cf8180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_details',
    sa.Column('studentid', sa.Integer(), nullable=False),
    sa.Column('studentname', sa.String(length=140), nullable=True),
    sa.Column('studentcontact', sa.Integer(), nullable=True),
    sa.Column('studentgender', sa.String(length=140), nullable=True),
    sa.Column('studentaddress', sa.String(length=140), nullable=True),
    sa.Column('user_idS', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_idS'], ['user.id'], ),
    sa.PrimaryKeyConstraint('studentid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_details')
    # ### end Alembic commands ###
