"""empty message

Revision ID: e2256fd36faf
Revises: dabc35687bdd
Create Date: 2019-12-12 22:56:56.251759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2256fd36faf'
down_revision = 'dabc35687bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_coaching_relation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('coaching_id', sa.Integer(), nullable=True),
    sa.Column('coachingTagIsActive', sa.String(length=140), nullable=True),
    sa.Column('CoachingStartDate', sa.String(length=140), nullable=True),
    sa.Column('CoachingEndDate', sa.String(length=140), nullable=True),
    sa.Column('CoachingStubject', sa.String(length=140), nullable=True),
    sa.Column('CoachingPaidAmount', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_coaching_relation')
    # ### end Alembic commands ###
