"""coachingclasses table

Revision ID: f3d19d240e09
Revises: 93edae68aacb
Create Date: 2019-08-15 17:38:54.258535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3d19d240e09'
down_revision = '93edae68aacb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaching_class',
    sa.Column('coachingid', sa.Integer(), nullable=False),
    sa.Column('coachingname', sa.String(length=140), nullable=True),
    sa.Column('coachingcontact', sa.Integer(), nullable=True),
    sa.Column('coachingemail', sa.String(length=140), nullable=True),
    sa.Column('coachingpassword_hash', sa.String(length=128), nullable=True),
    sa.Column('coachingabout', sa.String(length=140), nullable=True),
    sa.Column('coachingcoursesoffered', sa.String(length=140), nullable=True),
    sa.Column('coachingteachers', sa.String(length=140), nullable=True),
    sa.Column('coachingachievement', sa.String(length=140), nullable=True),
    sa.Column('coachingresults', sa.String(length=140), nullable=True),
    sa.Column('coachingcategory', sa.String(length=140), nullable=True),
    sa.Column('coachingsubcategory', sa.String(length=140), nullable=True),
    sa.Column('coachinglocation', sa.String(length=140), nullable=True),
    sa.PrimaryKeyConstraint('coachingid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coaching_class')
    # ### end Alembic commands ###
