"""empty message

Revision ID: fdea45df250d
Revises: 4bc6d443664e
Create Date: 2019-12-13 23:23:33.912019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdea45df250d'
down_revision = '4bc6d443664e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_coaching_relation', schema=None) as batch_op:
        batch_op.drop_column('CoachingStubject')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_coaching_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CoachingStubject', sa.VARCHAR(length=140), nullable=True))

    # ### end Alembic commands ###
