"""empty message

Revision ID: ff721ef063a1
Revises: d675de0baef2
Create Date: 2019-12-22 21:58:24.593552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff721ef063a1'
down_revision = 'd675de0baef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_coaching_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CoachingBatch', sa.Integer(), nullable=True))
        batch_op.drop_column('CoachingEndDate')
        batch_op.drop_column('CoachingStartDate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_coaching_relation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('CoachingStartDate', sa.VARCHAR(length=140), nullable=True))
        batch_op.add_column(sa.Column('CoachingEndDate', sa.VARCHAR(length=140), nullable=True))
        batch_op.drop_column('CoachingBatch')

    # ### end Alembic commands ###
